### ISSUE TITLE
UnhandledPromiseRejectionWarning when transferring clients to Clockify

### ISSUE THREAD

**Issue by YuvalGat** [mikerourke/toggl-to-clockify#17]
After running `toggl-to-clockify transfer -c t2c.json`, I get an `UnhandledPromiseRejectionWarning` when transferring clients to Clockify. Output below.

Node version: 11.5.0.
More information: my Clockify is completely empty as of now, while my Toggl has hundreds of time entries and many different projects.
This bug was mentioned in a comment in issue #12 . Any simple fix?
Thanks,
~Yuval

```Fetching workspaces from Toggl...
Fetching time entries and projects in workspace: Yuvalgat11...
Getting time entries for page 1 for Yuvalgat11 for the year of 2018...
Getting time entries for page 2 for Yuvalgat11 for the year of 2018...
Getting time entries for page 3 for Yuvalgat11 for the year of 2018...
Getting time entries for page 4 for Yuvalgat11 for the year of 2018...
Getting time entries for page 5 for Yuvalgat11 for the year of 2018...
Getting time entries for page 6 for Yuvalgat11 for the year of 2018...
Getting time entries for page 7 for Yuvalgat11 for the year of 2018...
Getting time entries for page 8 for Yuvalgat11 for the year of 2018...
Getting time entries for page 9 for Yuvalgat11 for the year of 2018...
Getting time entries for page 10 for Yuvalgat11 for the year of 2018...
Getting time entries for page 11 for Yuvalgat11 for the year of 2018...
Getting time entries for page 12 for Yuvalgat11 for the year of 2018...
Getting time entries for page 13 for Yuvalgat11 for the year of 2018...
Getting time entries for page 14 for Yuvalgat11 for the year of 2018...
Getting time entries for page 15 for Yuvalgat11 for the year of 2018...
Getting time entries for page 16 for Yuvalgat11 for the year of 2018...
Getting time entries for page 17 for Yuvalgat11 for the year of 2018...
Getting time entries for page 18 for Yuvalgat11 for the year of 2018...
Writing Toggl data to JSON file...
Toggl processing complete
Fetching workspaces from Clockify...
Getting clients for Yuvalgat11...
Getting projects for Yuvalgat11...
Getting tags for Yuvalgat11...
Transferring clients to Clockify in Yuvalgat11...
(node:34957) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of null
    at Clockify.<anonymous> (/Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:300:63)
    at step (/Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:43:23)
    at Object.next (/Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:24:53)
    at /Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:14:12)
    at Clockify.transferEntitiesFromToggl (/Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:293:16)
    at Clockify.<anonymous> (/Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:407:41)
    at step (/Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:43:23)
    at Object.next (/Users/yuvalgat/.nvm/versions/node/v11.5.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:24:53)
(node:34957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:34957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In thefuture, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by mikerourke** [comment]
@YuvalGat I completely forgot about this, my bad. I’m travelling today for the holiday, but I might be able to fix it tonight. I’ll keep you posted.

**Comment by YuvalGat** [comment]
Absolutely no worries. Thank a bunch!

**Comment by mikerourke** [comment]
@YuvalGat Could you try installing the latest version (`0.1.9`) and giving it another try?

**Comment by YuvalGat** [comment]
@mikerourke Huh, this bug seems to be gone but now I just get an infinite `Creating time entries for records n-n+25` loop, as in #10 . At first I thought I just had a ton of time entries but 4000 doesn't make much sense... Thanks!

**Comment by mikerourke** [comment]
@YuvalGat it’s like playing whack-a-mole! I’m actually working on a web-based version now that will address the current issues (I kind of cobbled this tool together and didn’t really design it to be robust). It should be ready in a week or so, would you be OK with waiting a little longer before doing the transfer?

**Comment by YuvalGat** [comment]
Haha, yeah! Take your time, it's nothing critical. Thanks!

**Comment by mikerourke** [comment]
Hey @YuvalGat, I'm planning on deprecating this library and redirecting everyone to that web-based version. I know I said it would be ready in a week back in December, but it turns out it was more like 5 months, so I was close! I'm planning on releasing the tool with single-user transfer functionality only (still working on multi-user) next week. I'll send you a link when it's ready. Sorry about the delay!
