### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: results.reduce is not a function

### ISSUE THREAD

**Issue by tjancz** [mikerourke/toggl-to-clockify#20]
Hello

During import data from Toggl I'm getting error:
`(node:4726) UnhandledPromiseRejectionWarning: TypeError: results.reduce is not a function
    at Clockify.<anonymous> (/home/tj/.nvm/versions/node/v11.11.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:518:44)
    at step (/home/tj/.nvm/versions/node/v11.11.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:43:23)
    at Object.next (/home/tj/.nvm/versions/node/v11.11.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:24:53)
    at fulfilled (/home/tj/.nvm/versions/node/v11.11.0/lib/node_modules/toggl-to-clockify/lib/tools/Clockify.js:15:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:4726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by mikerourke** [comment]
@tjancz Did you create the workspaces on Clockify first?

**Comment by tjancz** [comment]
Yes I did :(

**Comment by mikerourke** [comment]
I’m about a week and a half away from releasing my web-based version of this tool. Would you be OK with waiting to perform the transfer? I was planning on archiving this tool.

**Comment by mikerourke** [comment]
@tjancz Remember like a month ago when I said I was a week and a half away from being done? My estimation skills are terrible. I'm shooting for this Monday to have it ready, though. I'll send you a link to the hosted tool when it's up. Sorry about the delay!
